import type { Metadata } from "next";
import { Space_Mono, Kanit } from 'next/font/google';
import "./globals.css";

export const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-space-mono',
  display: 'swap',
});

export const kanit = Kanit({
  subsets: ['latin'],
  weight: [
    '100', '200', '300', '400', '500', '600', '700', '800', '900'
  ],
  style: ['normal', 'italic'],
  variable: '--font-kanit',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} ${spaceMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
